### ISSUE TITLE
Time Support in Date Property

### ISSUE THREAD

**Issue by flamedfury** [johnwargo/eleventy-new-post#2]
**What problem are you trying to solve with this feature?**
Time support alongside date during post creation

**Is your feature request related to a problem? Please describe.**
Posts that are missing timestamps when rendered in an RSS/feed all end up being posted at `00:00`. The feed also complains if there are more than one post per day because of this.

**Describe the solution you'd like**
I would love to have the time that the post was created to the `date` key, e.g. `date: 2024-04-05T20:07:30Z`

**Describe alternatives you've considered**
Manually adding in the timestamp once the post has been created.

**Comment by johnwargo** [comment]
Eleventy ignores the timestamp portion of the `date` property. In order to support timestamps, the utility would need to add an additional property to the front matter, I assume called `timestamp`, and put the full time there. 

Thanks for the suggestion, it would be really easy to add.

**Comment by johnwargo** [comment]
@flamedfury check it out
